import { BookOpen, ChevronDown } from "lucide-react";

export function AppHelp({ role }: { role: "admin" | "coach" | "parent" }) {
  return <details className="panel app-help">
    <summary><span className="panel-icon"><BookOpen size={18}/></span><span><strong>Hjälp · Så fungerar Matchkollen</strong><small>Från lag och spelare till match och statistik</small></span><ChevronDown size={18} className="help-chevron"/></summary>
    <div className="help-content">
      <p>Matchkollen samlar lag, matchtrupper, resultat och kort. Välj sport högst upp för att hålla exempelvis fotboll och innebandy åtskilda. Startsidan visar planerade matcher för ditt urval.</p>
      <section><h3>1. Konton, tränare och lagtillhörighet</h3><p>{role === "admin" ? "Under Användare skapar du konton eller redigerar befintliga konton. Välj Tränare och markera alla lag personen tränar, även i flera sporter. Spara kontot för att uppdatera kopplingen. Föräldrar tilldelas lag på samma sätt men kan bara läsa data. Du kan stänga av ett konto tillfälligt eller ta bort det permanent utan att lagens matchhistorik försvinner." : role === "coach" ? "Som tränare kan du registrera spelare och hantera matcher, mål och kort för dina tilldelade lag. Samma konto kan vara kopplat till flera lag i flera sporter. Kontakta administratören om ett lag saknas eller din lagtillhörighet behöver ändras." : "Som förälder kan du se tilldelade lags spelare, matcher, resultat och statistik. Du kan inte ändra uppgifterna. Kontakta administratören om ett lag saknas."}</p><p>Administratören hanterar sporter, lag och konton. Konton utan tilldelade lag får ingen tillgång till lagdata. Under Användare visas varje kopplat lag tillsammans med sin sport.</p></section>
      <section><h3>2. Registrera lag och spelare</h3><p>Administratören lägger först till sport och lag under Lag &amp; spelare. Därefter väljer administratören eller tränaren ett lag och registrerar spelarnas namn och eventuella tröjnummer. Spelarlistan tillhör laget; matchtruppen väljs separat för varje match.</p></section>
      <section><h3>3. Planera match, cup eller sammandrag</h3><p>Under Matcher väljer du lag och anger motståndare, datum, tid, plats och antal perioder. Välj vilka gula, röda och gröna kort som ska användas. För en cup eller ett sammandrag registrerar du flera matcher och ett gemensamt kortval. Matcherna sparas som Planerade. Välj deltagande spelare under Spelartrupp.</p><p>Med Redigera match kan du ändra inställningarna efteråt. Cupens gemensamma kortval ändras av administratören och gäller alla dess matcher. Lagbyte kräver att matchen saknar trupp, mål och kort.</p></section>
      <section><h3>4. Starta och registrera händelser</h3><p>Öppna matchen och välj Starta match. Kontrollera halvlek eller period innan du registrerar en händelse. Tryck på spelarens namn för ett mål och använd kortknapparna för aktiverade kort. Resultatets plus- och minusknappar används för att justera mål. Matchhändelser visar registrerade mål och kort, som sparas löpande.</p><p>Välj Spelartrupp under Matcher för att öppna matchinställningarna. Bocka i spelarna och spara matchinställningarna. En felregistrering kan rättas i matchloggen. Nollställ tar bort matchens händelser efter bekräftelse, så använd det bara när hela loggen ska tömmas.</p></section>
      <section><h3>5. Paus och fortsättning</h3><p>Vid paus eller periodbyte gör du uppehåll i registreringen och väljer nästa halvlek eller period när spelet fortsätter. Det finns ingen separat pausstatus eller matchklocka i den här versionen. Matchen ligger kvar som Pågående och sparade händelser behålls när du lämnar vyn och öppnar den igen.</p><p>Om matchen startades av misstag kan du på fliken Matcher välja Tillbaka till planerad. Trupp, mål och kort behålls.</p></section>
      <section><h3>6. Avsluta och hitta historiken</h3><p>När matchen är klar väljer du Avsluta match &amp; spara resultat. Den flyttas till Matcher → Historik och tas med i statistiken. Du kan öppna den där för att läsa resultatet eller, som tränare eller administratör, redigera inställningarna.</p><p>Om en match tas bort raderas även dess matchhändelser och statistikbidrag. Gamla avslutade matcher behöver tas bort i Historik om de inte ska finnas kvar.</p></section>
      <section><h3>7. Läs statistiken</h3><p>Statistik sammanställer avslutade matcher och matcher som har registrerade mål eller kort: resultat, mål, vinstandel, hållna nollor, målskyttar och kort. Filtrera på sport, lag, cup eller sammandrag och enskild match för att avgränsa jämförelsen. Även en pågående eller planerad match kan därför synas om den redan har mål eller kort. Matcher utan händelser syns först när de avslutas. Endast lag som ditt konto har tillgång till visas.</p></section>
      <section><h3>8. Spelarprofiler och profilbilder</h3><p>Under Lag &amp; spelare hittar du Spelarprofiler. Öppna en profil och koppla den till fler lag, med eget tröjnummer och aktiv status för varje lag. Namn och bild är gemensamma. Inaktivera en lagkoppling för att behålla historiken men ta bort spelaren ur den aktiva truppen. Administratören kan koppla mellan alla lag; tränare hanterar profiler som redan är tillgängliga i deras tilldelade lag.</p><p>Öppna Profilbild, välj en JPEG-, PNG- eller WebP-bild och centrera med dragning eller reglage. Zooma tills den runda förhandsvisningen ser rätt ut och välj Spara bild. Bilden kan bytas eller tas bort. På Start kan alla användare ändra sin egen profilbild. Admin ändrar tränarnas och föräldrarnas bilder under Användare → Redigera.</p></section>
      <section><h3>9. Barn, föräldrar och sportavatarer</h3><p>Spelarprofiler visas som kompakta rader. Klicka på en spelare för alla uppgifter och åtgärder. Inaktivera spelare gäller alla lag och kan ångras med Aktivera spelare. Ta bort permanent raderar profil, bild och kopplingar, men sparade matchhändelser behålls. Tränare kan hantera hela profilen om de har tillgång till samtliga lag; annars behövs admin. Admin kan inaktivera eller permanent ta bort tränar- och föräldrakonton under Användare.</p><p>Admin kan välja barnens spelarprofiler när ett tränar- eller föräldrakonto skapas eller redigeras. När en ny spelare registreras kan befintliga tränar- eller föräldrakonton väljas direkt. I spelarprofilen går det även att ändra kopplingen senare. En tränare kan också vara förälder till flera barn och behåller sina tränarbehörigheter. Ett barn kan ha flera föräldrar och ett föräldrakonto kan kopplas till flera barn. Barnen är spelarprofiler och har inga egna inloggningskonton. Familjekopplingen ändrar inte lagbehörigheten; admin väljer fortfarande vilka lag föräldern får följa.</p><p>I bildverktyget finns Välj en rolig sportavatar med 20 maskotar för fotboll och innebandy. Välj en, kontrollera förhandsvisningen och klicka på Spara bild. Samma avatarer kan användas av spelare, tränare och föräldrar.</p></section>
      {role === "admin" && <section><h3>Aktivitetslogg för admin</h3><p>Under Aktivitetslogg ser du inloggningar, utloggningar och dataändringar från och med den här uppdateringen. Filtrera på användare, datum och typ och välj Visa äldre poster för mer historik. Tid visas i svensk tid. Användarnas namn behålls i loggen även efter att ett konto tas bort. Vanlig visning, lösenord och bildinnehåll sparas inte i loggen.</p></section>}
      <section><h3>10. Välj utseende</h3><p>Med Färgtema högst upp väljer du Ljust, Mörkt eller System. System följer enhetens inställning. Valet sparas i den webbläsare du använder.</p></section>
    </div>
  </details>;
}
